package pascal.lexico;

public enum ClasseToken {
    IDENTIFICADOR,
    NUMERO_INTEIRO,
    CADEIA_DE_CARACTERES,
    ADICAO,
    SUBTRACAO,
    MULTIPLICACAO,
    DIVISAO,
    PAR_ESQUERDA,
    PAR_DIREITA,
    PONTO_VIRGULA,
    VIRGULA,
    PONTO,
    DOIS_PONTOS,
    MAIOR,
    MAIOR_IGUAL,
    MENOR,
    MENOR_IGUAL,
    IGUAL,
    DIFERENTE,
    ATRIBUICAO,
    PALAVRA_RESERVADA,
    EOF
}
